version: '3.9'

services:
  db:
    container_name: mysql8
    hostname: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: StoneScissorsPaper
      MYSQL_USER: stscpa
      MYSQL_PASSWORD: stscpa1stscpa
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
#    volumes:
#      - './docker/db/data:/var/lib/mysql'
#      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
#      - './sql:/docker-entrypoint-initdb.d'

  server:
    container_name: server
    depends_on:
      - db
    build:
      context: server
    image: server:latest
    ports:
      - 54555:54555
    environment:
      WAIT_HOSTS: db:3306
      MYSQL_HOST: db
      MYSQL_USER: stscpa
      MYSQL_PWD: stscpa1stscpa